# Generated by Django 5.2.2 on 2025-06-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.URLField()),
                ('content', models.TextField()),
                ('document', models.FileField(upload_to='documents')),
            ],
        ),
    ]
