# Generated by Django 5.2.1 on 2025-06-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oracle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainningData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='trainning',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('trainning_data', models.ManyToManyField(to='oracle.trainningdata')),
            ],
        ),
    ]
